version: 0.1

run-as: peter

phases:
  build:
    on-failure: ABORT
    commands:
      - ./build_and_push.sh
artifacts:
  files:
    - 'Dockerrun.aws.json'

eb_codebuild_settings:
  CodeBuildServiceRole: CodeBuildServiceRole1
  ComputeType: BUILD_GENERAL1_LARGE
  Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
  Timeout: 60
