version: 0.1

run-as: peter

phases:
  install:
    on-failure: ABORT
    commands:
      - echo "4:38PM"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 947734355387.dkr.ecr.us-east-1.amazonaws.com
  build:
    on-failure: ABORT
    commands:
      - ./build_and_push.sh
  # post_build:
  #   on-failure: ABORT
  #   commands:
  #     - cd eb
  #     - echo '\n====== Deploying to Elastic Beanstalk ======\n'
  #     - eb deploy
artifacts:
  files:
    - 'Dockerrun.aws.json'

eb_codebuild_settings:
  CodeBuildServiceRole: CodeBuildServiceRole1
  ComputeType: BUILD_GENERAL1_LARGE
  Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
  Timeout: 10
